version: '2'
services:
  django:
    restart: always
    build:
        context: ./backend
    volumes:
      - ./backend:/app/backend
    links:
      - react
    # expose:
    #     - 8000
    # ports:
    #   - 8000:8000
  # redis:
  #   image: "redis:alpine"

  # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
  react-proxy:
    restart: always
    build:
      context: ./proxy
    expose:
      - 4000
    ports:
      - 80:4000
    volumes:
      - ./proxy:/app/proxy
      - /app/proxy/node_modules
    links:
      - react
      - django

  react:
    restart: always
    build:
      context: ./frontend
    # expose:
    #   - 3000
    # ports:
    #   - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  # postgres:
  #   restart: always
  #   image: postgres:9.5.4
  #   expose:
  #       - 5432
  #   volumes:
  #     - ./docker/postgres/data:/var/lib/postgresql
